DROP TABLE LINKS;

CREATE TABLE LINKS(
	Id INT NOT NULL AUTO_INCREMENT,
	Link VARCHAR(2000) NOT NULL,
	LinkHash BINARY(160) NOT NULL,
	Visited BOOLEAN NOT NULL DEFAULT FALSE,
	Score INT NOT NULL DEFAULT 0,
	PRIMARY KEY (Id)
);

CREATE INDEX idx_links ON LINKS(LinkHash);
