DROP TABLE LINKS;
DROP TABLE DOMAINS;

CREATE TABLE DOMAINS(
	Id INT AUTO_INCREMENT,
	LinkDomain VARCHAR(255) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE LINKS(
	Id INT NOT NULL AUTO_INCREMENT,
	IdDomain INT NOT NULL,
	Link VARCHAR(2000) NOT NULL,
	LinkHash BINARY(160) NOT NULL,
	Visited BOOLEAN NOT NULL DEFAULT FALSE,
	Score INT NOT NULL DEFAULT 1,
	Metadata BLOB,
	PRIMARY KEY (Id),
	FOREIGN KEY (IdDomain) REFERENCES DOMAINS(Id)
);

CREATE UNIQUE INDEX idx_doamins ON DOMAINS(LinkDomain);
CREATE INDEX idx_links ON LINKS(LinkHash);
